<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <Nullable>enable</Nullable>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutDir>..\..\Bin</OutDir>
      <AssemblyName>Demos.Web</AssemblyName>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
   </PropertyGroup>
   <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0-*" />
   </ItemGroup>
   <ItemGroup>
      <ProjectReference Include="..\..\Core\Nori.Core.csproj" />
      <ProjectReference Include="..\..\Lux\Nori.Lux.csproj" />
      <ProjectReference Include="..\..\GPU.Web\Nori.GPU.Web.csproj" />
      <ProjectReference Include="..\Shared\Demos.Shared.csproj" />
      <ProjectReference Include="..\..\Platform.Web\Nori.Platform.Web.csproj" />
   </ItemGroup>
   <ItemGroup>
      <ProjectReference Include="..\..\Tools\Generate\Nori.Gen.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
   </ItemGroup>
</Project>
