<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <OutputType>WinExe</OutputType>
      <TargetFramework>net10.0-windows</TargetFramework>
      <Nullable>enable</Nullable>
      <UseWPF>true</UseWPF>
      <UseWindowsForms>true</UseWindowsForms>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutDir>..\..\Bin</OutDir>
      <AssemblyName>Demos.Windows</AssemblyName>
      <EnableWindowsTargeting>true</EnableWindowsTargeting>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
   </PropertyGroup>
   <ItemGroup>
      <ProjectReference Include="..\..\Core\Nori.Core.csproj" />
      <ProjectReference Include="..\..\Lux\Nori.Lux.csproj" />
      <ProjectReference Include="..\..\GPU\Nori.GPU.csproj" />
      <ProjectReference Include="..\Shared\Demos.Shared.csproj" />
      <ProjectReference Include="..\..\Platform.Windows\Nori.Platform.Windows.csproj" />
   </ItemGroup>
   <ItemGroup>
      <ProjectReference Include="..\..\Tools\Generate\Nori.Gen.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
   </ItemGroup>
</Project>
