// ────── ╔╗                                                                                   CORE
// ╔═╦╦═╦╦╬╣ Tess2D.cs
// ║║║║╬║╔╣║ Pure C# 2D tessellator using LibTessDotNet (GLU tessellation algorithm port)
// ╚╩═╩═╩╝╚╝ ───────────────────────────────────────────────────────────────────────────────────────
using LibTessDotNet;
namespace Nori;

#region class Tess2D -------------------------------------------------------------------------------
/// <summary>Given a list of points as inner and outer polygon contours, generate a tessellation in 2D</summary>
/// This tessellator uses LibTessDotNet, a pure C# port of the OpenGL GLU tessellation library.
/// <param name="pts">Set of all contour points</param>
/// <param name="splits">Contour indices in the points array. E.g: [0, 10, 14] has two contours [0, 10) and [10, 14)</param>
public class Tess2D (List<Point2> pts, IReadOnlyList<int> splits) {
   /// <summary>What is the minimum area of triangles below which they are rejected?</summary>
   public double MinArea { get; set; } = 1E-12;

   /// <summary>Tessellates the polygons with outer and inner contours into triangles</summary>
   /// <returns>The triangle indices into the original pts list</returns>
   public static List<int> Process (List<Point2> pts, IReadOnlyList<int> splits)
      => new Tess2D (pts, splits).Process ();

   /// <summary>Perform the tessellation</summary>
   public List<int> Process () {
      var tess = new Tess ();

      // Add each contour to the tessellator
      for (int i = 1; i < mSplit.Count; i++) {
         int a = mSplit[i - 1], b = mSplit[i];
         int count = b - a;
         if (count < 3) continue;
         var contour = new ContourVertex[count];
         for (int j = 0; j < count; j++) {
            var pt = mPts[a + j];
            contour[j].Position = new Vec3 ((float)pt.X, (float)pt.Y, 0);
            contour[j].Data = a + j; // Store original index
         }
         tess.AddContour (contour);
      }

      // Run tessellation with winding rule Odd (matches GLU default for polygon-with-holes)
      tess.Tessellate (WindingRule.EvenOdd, ElementType.Polygons, 3, VertexCombine);

      // Extract triangle indices, mapping back to original point indices
      var result = new List<int> ();
      if (tess.Elements == null || tess.Vertices == null) return result;

      for (int i = 0; i < tess.ElementCount; i++) {
         int i0 = tess.Elements[i * 3];
         int i1 = tess.Elements[i * 3 + 1];
         int i2 = tess.Elements[i * 3 + 2];
         if (i0 < 0 || i1 < 0 || i2 < 0) continue;

         // Map tessellator vertex indices to original point indices
         int n0 = VertexIndex (tess.Vertices[i0]);
         int n1 = VertexIndex (tess.Vertices[i1]);
         int n2 = VertexIndex (tess.Vertices[i2]);

         // Filter degenerate triangles by area
         var p0 = GetPoint (tess.Vertices[i0], n0);
         var p1 = GetPoint (tess.Vertices[i1], n1);
         var p2 = GetPoint (tess.Vertices[i2], n2);
         double area = Math.Abs ((p1.X - p0.X) * (p2.Y - p0.Y) - (p2.X - p0.X) * (p1.Y - p0.Y)) * 0.5;
         if (area < MinArea) continue;

         result.Add (n0);
         result.Add (n1);
         result.Add (n2);
      }
      return result;
   }

   // Private helpers -----------------------------------------------------------

   /// <summary>Get the original point index from a tessellator vertex</summary>
   int VertexIndex (ContourVertex v) {
      if (v.Data is int idx) return idx;
      // Combined vertex — find or add to pts
      return AddCombinedVertex (v.Position.X, v.Position.Y);
   }

   /// <summary>Get Point2 coordinates, preferring original point data when available</summary>
   Point2 GetPoint (ContourVertex v, int idx) {
      if (idx < mPts.Count) return mPts[idx];
      return new Point2 (v.Position.X, v.Position.Y);
   }

   /// <summary>Add a new vertex generated by the tessellator's combine callback</summary>
   int AddCombinedVertex (double x, double y) {
      mPts.Add (new Point2 (x, y));
      return mPts.Count - 1;
   }

   /// <summary>Combine callback for LibTessDotNet — called when edges intersect</summary>
   static object VertexCombine (Vec3 position, object[] data, float[] weights) {
      // Return index of first contributing vertex as a fallback;
      // the actual mapping happens in VertexIndex which checks position
      // For combined vertices, return null — VertexIndex will add to pts
      return null!;
   }

   // Private data -------------------------------------------------------------
   readonly List<Point2> mPts = pts;
   readonly IReadOnlyList<int> mSplit = splits;
}
#endregion
