<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net10.0</TargetFramework>
      <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
      <Nullable>enable</Nullable>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <OutDir>..\..\Bin</OutDir>
      <AssemblyName>Demos.macOS</AssemblyName>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
   </PropertyGroup>
   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
   </PropertyGroup>
   <ItemGroup>
      <ProjectReference Include="..\..\Core\Nori.Core.csproj" />
      <ProjectReference Include="..\..\Lux\Nori.Lux.csproj" />
      <ProjectReference Include="..\..\GPU\Nori.GPU.csproj" />
      <ProjectReference Include="..\Shared\Demos.Shared.csproj" />
      <ProjectReference Include="..\..\Platform.Desktop\Nori.Platform.Desktop.csproj" />
   </ItemGroup>
   <ItemGroup>
      <ProjectReference Include="..\..\Tools\Generate\Nori.Gen.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
   </ItemGroup>
</Project>
